export const typographyData = [
  {
    name: "Heading 1 - 32px Bold",
    font: "Inter",
    size: "2rem",
    weight: "700",
    letterSpacing: "-0.02em",
    lineHeight: "1.2",
    usage: "Used for main page titles and hero sections",
    borderColorClassName: "border-primary-600",
    sampleClassName: "text-[2rem] font-bold tracking-[-0.02em] leading-[1.2]",
  },
  {
    name: "Heading 2 - 24px Semibold",
    font: "Inter",
    size: "1.5rem",
    weight: "600",
    letterSpacing: "-0.01em",
    lineHeight: "1.3",
    usage: "Used for section headings and major content blocks",
    borderColorClassName: "border-primary-500",
    sampleClassName: "text-2xl font-semibold tracking-[-0.01em] leading-[1.3]",
  },
  {
    name: "Heading 3 - 20px Semibold",
    font: "Inter",
    size: "1.25rem",
    weight: "600",
    letterSpacing: "0em",
    lineHeight: "1.4",
    usage: "Used for subsection headings and card titles",
    borderColorClassName: "border-primary-400",
    sampleClassName: "text-xl font-semibold tracking-normal leading-[1.4]",
  },
  {
    name: "Body Large - 18px Medium",
    font: "Inter",
    size: "1.125rem",
    weight: "500",
    letterSpacing: "0em",
    lineHeight: "1.5",
    usage: "Used for lead paragraphs and important text",
    borderColorClassName: "border-primary-300",
    sampleClassName: "text-lg font-medium tracking-normal leading-[1.5]",
  },
  {
    name: "Body - 16px Regular",
    font: "Inter",
    size: "1rem",
    weight: "400",
    letterSpacing: "0em",
    lineHeight: "1.5",
    usage: "Used for main body text and descriptions",
    borderColorClassName: "border-primary-200",
    sampleClassName: "text-base font-normal tracking-normal leading-[1.5]",
  },
  {
    name: "Body Small - 14px Regular",
    font: "Inter",
    size: "0.875rem",
    weight: "400",
    letterSpacing: "0em",
    lineHeight: "1.5",
    usage: "Used for secondary text and captions",
    borderColorClassName: "border-primary-100",
    sampleClassName: "text-sm font-normal tracking-normal leading-[1.5]",
  },
  {
    name: "Caption - 12px Regular",
    font: "Inter",
    size: "0.75rem",
    weight: "400",
    letterSpacing: "0em",
    lineHeight: "1.5",
    usage: "Used for labels, timestamps, and micro-copy",
    borderColorClassName: "border-slate-70",
    sampleClassName: "text-xs font-normal tracking-normal leading-[1.5]",
  },
];
